
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:products_db}?sslmode=disable
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}   # <-- change '0000' en 'postgres'

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: Africa/Tunis

server:
  port: ${SERVER_PORT:8081}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
